repos:
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.8.0
    hooks:
    - id: isort
      files: ^systole/
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
      files: ^systole/
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
      files: ^systole/
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    - id: mypy 
      files: ^systole/
      args: [--ignore-missing-imports]